#!/usr/bin/env python

from flask import Flask
import pymysql.cursors
import os

app = Flask(__name__)

@app.route('/')
def hello_world():
    return "Hello World!"

@app.route('/user/')
def user():
    connection = pymysql.connect(
        host=os.environ['DOCKERTIPS7_MYSQL_HOSTNAME'],
        user='root',
        password=os.environ['DOCKERTIPS7_MYSQL_PASSWD'],
        db='web',
        charset='utf8',
        cursorclass=pymysql.cursors.DictCursor)
    try:
        with connection.cursor() as cursor:
            sql = "SELECT name FROM user"
            cursor.execute(sql)
            return ','.join([r['name'] for r in cursor.fetchall()])
    finally:
        connection.close()

if __name__ == '__main__':
    app.run(host='0.0.0.0')
